name: lsd
version: git
summary: A ls command with a lot of pretty colors.
description: lsd is a ls command including pretty icons based on nerd-font.

architectures:
  - amd64
grade: stable
confinement: classic

parts:
  lsd:
    plugin: rust
    source: ./

apps:
  lsd:
    command: bin/lsd
