[package]
authors = ["Peltoche <dev@halium.fr>"]
build = "build.rs"
categories = ["command-line-utilities"]
description = "An ls command with a lot of pretty colors and some other stuff."
keywords = ["ls"]
license = "Apache-2.0"
name = "lsd"
readme = "./README.md"
repository = "https://github.com/Peltoche/lsd"
version = "0.14.0"
edition = "2018"

[[bin]]
name = "lsd"
path = "src/main.rs"

[build-dependencies]
clap = "2.32.0"
version_check = "0.1.3"

[dependencies]
ansi_term = "0.11.0"
libc = "0.2.44"
term_grid = "0.1.7"
terminal_size = "0.1.8"
time = "0.1.40"
chrono-humanize = "0.0.11"
unicode-width = "0.1.5"
lscolors = "0.5.0"

[target.'cfg(unix)'.dependencies]
users = "0.9.0"

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3.6", features = ["aclapi", "accctrl", "winnt", "winerror", "securitybaseapi", "winbase"]}

[dependencies.clap]
features = ["suggestions", "color", "wrap_help"]
version = "2.32.0"

[dev-dependencies]
tempdir = "0.3.7"

[features]
sudo = []
